AppBundle\Entity\CompanyProductMap:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    manyToOne:
        company:
            targetEntity: AppBundle\Entity\Company
            inversedBy: companyProductMaps
            cascade: ["persist", "remove", "remove"]
        product:
            targetEntity: AppBundle\Entity\Product
            inversedBy: companyProductMaps
            cascade: ["persist", "remove", "remove"]

    lifecycleCallbacks: {  }
